name: movie_search_challenge
description: "Movie Search Challenge"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  auto_route: ^10.1.0+1
  bloc: ^9.0.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  http: ^1.4.0
  injectable: ^2.5.0
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  auto_route_generator: ^10.2.3
  bloc_test: ^10.0.0
  build_runner:
  coverage: ^1.15.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - .env