name: CI

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main

jobs:
  analyze-test-build:
    name: Analyze, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Remove generated files
        run: |
          find . -type f \( -name "*.g.dart" -o -name "*.freezed.dart" -o -name "*.mocks.dart" \) -delete

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Clean build artifacts
        run: flutter pub run build_runner clean

      - name: Build generated code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Create dummy .env
        run: echo "OMDB_API_KEY=DUMMY" > .env

      - name: Static analysis
        run: flutter analyze

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Enforce coverage ≥ 80%
        uses: VGVentures/very-good-coverage@v1.1.1
        with:
          path: coverage/lcov.info
          min_coverage: 80

      - name: Build Android release
        run: flutter build appbundle --release

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info
